/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: {
          50: 'hsl(var(--color-primary) / 0.05)',
          100: 'hsl(var(--color-primary) / 0.1)',
          200: 'hsl(var(--color-primary) / 0.2)',
          300: 'hsl(var(--color-primary) / 0.3)',
          400: 'hsl(var(--color-primary) / 0.4)',
          500: 'hsl(var(--color-primary) / 0.5)',
          600: 'hsl(var(--color-primary) / 0.6)',
          700: 'hsl(var(--color-primary) / 0.7)',
          800: 'hsl(var(--color-primary) / 0.8)',
          900: 'hsl(var(--color-primary) / 0.9)',
          950: 'hsl(var(--color-primary) / 0.95)',
        },
        secondary: {
          50: 'hsl(var(--color-secondary) / 0.05)',
          100: 'hsl(var(--color-secondary) / 0.1)',
          200: 'hsl(var(--color-secondary) / 0.2)',
          300: 'hsl(var(--color-secondary) / 0.3)',
          400: 'hsl(var(--color-secondary) / 0.4)',
          500: 'hsl(var(--color-secondary) / 0.5)',
          600: 'hsl(var(--color-secondary) / 0.6)',
          700: 'hsl(var(--color-secondary) / 0.7)',
          800: 'hsl(var(--color-secondary) / 0.8)',
          900: 'hsl(var(--color-secondary) / 0.9)',
          950: 'hsl(var(--color-secondary) / 0.95)',
        },
        accent: {
          50: 'hsl(var(--color-accent) / 0.05)',
          100: 'hsl(var(--color-accent) / 0.1)',
          200: 'hsl(var(--color-accent) / 0.2)',
          300: 'hsl(var(--color-accent) / 0.3)',
          400: 'hsl(var(--color-accent) / 0.4)',
          500: 'hsl(var(--color-accent) / 0.5)',
          600: 'hsl(var(--color-accent) / 0.6)',
          700: 'hsl(var(--color-accent) / 0.7)',
          800: 'hsl(var(--color-accent) / 0.8)',
          900: 'hsl(var(--color-accent) / 0.9)',
          950: 'hsl(var(--color-accent) / 0.95)',
        },
        success: {
          50: 'hsl(var(--color-success) / 0.05)',
          100: 'hsl(var(--color-success) / 0.1)',
          200: 'hsl(var(--color-success) / 0.2)',
          300: 'hsl(var(--color-success) / 0.3)',
          400: 'hsl(var(--color-success) / 0.4)',
          500: 'hsl(var(--color-success) / 0.5)',
          600: 'hsl(var(--color-success) / 0.6)',
          700: 'hsl(var(--color-success) / 0.7)',
          800: 'hsl(var(--color-success) / 0.8)',
          900: 'hsl(var(--color-success) / 0.9)',
          950: 'hsl(var(--color-success) / 0.95)',
        },
        warning: {
          50: 'hsl(var(--color-warning) / 0.05)',
          100: 'hsl(var(--color-warning) / 0.1)',
          200: 'hsl(var(--color-warning) / 0.2)',
          300: 'hsl(var(--color-warning) / 0.3)',
          400: 'hsl(var(--color-warning) / 0.4)',
          500: 'hsl(var(--color-warning) / 0.5)',
          600: 'hsl(var(--color-warning) / 0.6)',
          700: 'hsl(var(--color-warning) / 0.7)',
          800: 'hsl(var(--color-warning) / 0.8)',
          900: 'hsl(var(--color-warning) / 0.9)',
          950: 'hsl(var(--color-warning) / 0.95)',
        },
        error: {
          50: 'hsl(var(--color-error) / 0.05)',
          100: 'hsl(var(--color-error) / 0.1)',
          200: 'hsl(var(--color-error) / 0.2)',
          300: 'hsl(var(--color-error) / 0.3)',
          400: 'hsl(var(--color-error) / 0.4)',
          500: 'hsl(var(--color-error) / 0.5)',
          600: 'hsl(var(--color-error) / 0.6)',
          700: 'hsl(var(--color-error) / 0.7)',
          800: 'hsl(var(--color-error) / 0.8)',
          900: 'hsl(var(--color-error) / 0.9)',
          950: 'hsl(var(--color-error) / 0.95)',
        },
        gray: {
          50: 'hsl(var(--color-gray-50) / 1)',
          100: 'hsl(var(--color-gray-100) / 1)',
          200: 'hsl(var(--color-gray-200) / 1)',
          300: 'hsl(var(--color-gray-300) / 1)',
          400: 'hsl(var(--color-gray-400) / 1)',
          500: 'hsl(var(--color-gray-500) / 1)',
          600: 'hsl(var(--color-gray-600) / 1)',
          700: 'hsl(var(--color-gray-700) / 1)',
          800: 'hsl(var(--color-gray-800) / 1)',
          900: 'hsl(var(--color-gray-900) / 1)',
        },
      },
      spacing: {
        '72': '18rem',
        '80': '20rem',
        '96': '24rem',
        '128': '32rem',
      },
      fontFamily: {
        sans: [
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          '"Helvetica Neue"',
          'Arial',
          '"Noto Sans"',
          'sans-serif',
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
        'slide-left': 'slideLeft 0.3s ease-out',
        'slide-right': 'slideRight 0.3s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideLeft: {
          '0%': { transform: 'translateX(20px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        slideRight: {
          '0%': { transform: 'translateX(-20px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
};